### PR TITLE
Clean up on the contactus and shortlisting section

### PR DESCRIPTION
**Pull request by nuelAY**
## Description

Code adjustment

Fixes # (issue)
Corrected the button at the ShortListing screen  and adjusted the size of the mail and telephone icons in the contact us screen
## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by nuelAY** [comment]
You can check again, the conflicts have been resolved

**Comment by Blossom1-chike** [comment]
> You can check again, the conflicts have been resolved

i can still see conflicts in these files:
src/components/FAQ/Faq.tsx
src/components/ShortListing/ShortListingSection.tsx

in your branch, pull from the main branch. you should see the conflicts, resolve them while making sure that you don;t lose your code and that of the main branch
let me know if you want us to hop on a call

**Comment by nuelAY** [comment]
> > You can check again, the conflicts have been resolved
> 
> i can still see conflicts in these files: src/components/FAQ/Faq.tsx src/components/ShortListing/ShortListingSection.tsx
> 
> in your branch, pull from the main branch. you should see the conflicts, resolve them while making sure that you don;t lose your code and that of the main branch let me know if you want us to hop on a call

Okay, I'd do that

**Comment by nuelAY** [comment]
You can check now

**Comment by Blossom1-chike** [comment]
image
this "our links" section isn't positioned right, please confirm with the design

**Comment by Blossom1-chike** [comment]
also, on the contact form template file, change the input tags you're using to the TextInput component created, and observe the space between the label and input field

**Comment by Blossom1-chike** [comment]
confirm the font style used in the Contact Faq section on the design and update that on your code

**Review by Blossom1-chike — CHANGES_REQUESTED** [review]
check comments on the conversations thread

**Review by Blossom1-chike — APPROVED** [review]

**Pull request merged**
