### PR TITLE
pushing what i have worked on in company-profile again and trying to …

### PR DESCRIPTION
**Pull request by Ajinormotor**
…commit

## Description

Please include a summary of the changes and the related issue.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by Blossom1-chike — CHANGES_REQUESTED** [review]
@Ajinormotor please look into the mobile view of this company profile screen, i made edits to the web, so try to make it align with the mobile just as it is on the design.
- the swiper isn't well aligned
- the hero chunk also, ensure it displays as it is on the design
- make sure to not use the <button> tags anywhere because we have the button component already created except the design doesn't cater for it

**Comment by Ajinormotor** [comment]
swiper changes: added more height to it,
hero changes:  added flex-col to mobile and replaced the button tag with div

**Review by Ajinormotor — COMMENTED** [review]
swiper changes: added more height to it,
hero changes: added flex-col to mobile and replaced the button tag with div

**Review by Blossom1-chike — CHANGES_REQUESTED** [review]
image
@Ajinormotor please look into this

**Review by Blossom1-chike — CHANGES_REQUESTED** [review]
image

ensure the image takes the entire width of the page for smaller screens, also look into the space between the images and the "Partners" heading

**Review by Blossom1-chike — CHANGES_REQUESTED** [review]
image

ensure each cards takes its full width such that all four cards are flexed horizontally without any space beside like in this picture

**Review by Ajinormotor — COMMENTED** [review]
seen all changes and made all necessary  corrrection

**Review by Blossom1-chike — APPROVED** [review]

**Pull request merged**
